version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: auto-inventory-db
    restart: always
    environment:
      MYSQL_DATABASE: autoinventory
      MYSQL_USER: autouser
      MYSQL_PASSWORD: autopass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uautouser", "-pautopass"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s

  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: auto-inventory-app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: autoinventory
      DB_USERNAME: autouser
      DB_PASSWORD: autopass
    depends_on:
      db:
        condition: service_healthy

  web:
    image: nginx:1.27-alpine
    container_name: auto-inventory-web
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  vite:
    image: node:20-alpine
    container_name: auto-inventory-vite
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    # npm install + vite dev server with host 0.0.0.0 for Docker networking
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173 --strictPort"
    ports:
      - "5173:5173"
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: auto-inventory-phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: autouser
      PMA_PASSWORD: autopass
    ports:
      - "8081:80"

volumes:
  mysql_data:
